let prompts = ["Share a moment when you were proud of yourself.",
"What is something you've overcome in your life?",
"What personal trait has gotten you in the most trouble?",
"Describe a time when you failed at something, and what you learned from it.",
"What's something you need to forgive yourself for?",
"What are your top five personal values?",
"What personal habit would you like to change?",
"When do you feel most confident?",
"What does happiness mean to you?",
"What is your biggest regret and why?",
"What is the best advice you've ever received?",
"What life lesson did you learn the hard way?",
"How do you handle stress and pressure?",
"What are you most afraid of and why?",
"Describe an instance when you were courageous.",
"What inspires you?",
"What's something about yourself you'd like to improve?",
"When do you feel the most loved?",
"What do you wish others knew about you?",
"What's a quote that resonates with you?",
"If you could change one thing about yourself, what would it be?",
"What do you do to feel good about yourself?",
"What are your dreams and aspirations?",
"How have your priorities changed over time?",
"What is the greatest challenge you've faced in your life?",
"Who has had the biggest influence on your life?",
"What motivates you?",
"How do you handle criticism?",
"How do you define success?",
"When do you feel most authentic?",
"What kind of person do you aspire to be?",
"What’s a belief that you hold with which many people disagree?",
"What are you most grateful for?",
"How do you recharge?",
"What are your top three strengths and weaknesses?",
"How do you handle uncertainty?",
"What's the most important thing you've learned in your life so far?",
"Describe a time when you stood up for yourself.",
"How do you handle conflicts?",
"What's the best compliment you've ever received?",
"How do you express your anger?",
"What are you most passionate about?",
"What's a decision you've made that you're proud of?",
"How do you define self-love?",
"What role does faith play in your life?",
"What's the kindest thing you've ever done for someone?",
"How have your experiences shaped you?",
"What does a perfect day look like to you?",
"What’s something you always procrastinate on?",
"What are your top five long-term and short-term goals?",
"Describe your most cherished friendship.",
"What qualities do you value most in your friends?",
"How do you handle conflicts in your relationships?",
"Describe a time when you felt lonely.",
"What's the best relationship advice you've ever received?",
"What has been your most challenging relationship and why?",
"What do you think makes a relationship healthy?",
"How do you express love and how do you prefer to receive it?",
"Who is your role model for a good relationship and why?",
"How have your relationships changed over time?",
"What is your biggest challenge in social situations?",
"What's a friendship you regret ending?",
"How do you feel about online friendships and relationships?",
"What's the best way to maintain long-distance relationships?",
"What's the most valuable lesson you've learned from a previous relationship?",
"How do you deal with toxic relationships?",
"How do you celebrate your relationships?",
"Who is a person you could never imagine your life without?",
"What's a common misconception people have about you?",
"Describe a time you were a good friend.",
"What's your favorite way to meet new people?",
"What do you think about social media and its impact on relationships?",
"What is the role of trust in your relationships?",
"What does a good work relationship look like?",
"How do you balance your personal and professional relationships?",
"How have your friendships changed as you've grown older?",
"What's your opinion on workplace friendships?",
"How do you handle rejections?",
"What do you do to mend a broken relationship?",
"Describe a moment when you felt betrayed.",
"What’s the most interesting conversation you’ve had recently?",
"How do you maintain your relationships?",
"What's the importance of communication in your relationships?",
"How do you navigate family relationships?",
"How important are your friends in your life?",
"How do you handle jealousy in relationships?",
"What does 'family' mean to you?",
"How do you feel about public displays of affection?",
"How do you handle social pressure?",
"What's the most memorable gift you've ever received from a friend?",
"Who is your oldest friend, and how have you both changed since you first met?",
"Describe a time when you had to set boundaries in a relationship.",
"How do you balance giving and receiving in your relationships?",
"What is a deal-breaker for you in a relationship?",
"What is the importance of forgiveness in your relationships?",
"Describe a time when a friend helped you in a time of need.",
"How do you make new friends as an adult?",
"How do you handle the end of a relationship?",
"What role do your friends play in your life?",
"What's the best way to show appreciation to a friend?",
"What hobbies do you enjoy in your free time?",
"How have your hobbies evolved over time?",
"What's a hobby you've always wanted to start but never have?",
"What hobby brings you the most joy and why?",
"What's the last hobby you picked up and why did you choose it?",
"How have your hobbies helped you in your personal or professional life?",
"What's the most challenging hobby you've ever had?",
"How do you balance your hobbies with your work/life commitments?",
"What's a hobby you wish you had more time for?",
"How do your hobbies reflect your personality?",
"What was your favorite childhood hobby and do you still enjoy it?",
"How do your hobbies help you relax and de-stress?",
"What's a hobby you can lose hours to and not even notice?",
"What's the most unique or unusual hobby you've ever had or heard of?",
"How do you discover new hobbies or interests?",
"How do you feel when you share your hobbies with others?",
"Have you ever turned a hobby into a business?",
"What's a hobby you've picked up from a friend or family member?",
"Have you ever given up on a hobby, and if so, why?",
"How has a hobby challenged you in ways you didn't expect?",
"Have your hobbies helped you connect with others? How?",
"What's a hobby you wish was more socially acceptable?",
"How do your hobbies keep you inspired or motivated?",
"Do you prefer hobbies that you can do alone or with others?",
"How do you explore and cultivate your passions?",
"How have your hobbies helped you grow as a person?",
"What's the most rewarding part about engaging in your hobby?",
"Have you ever had a hobby that others didn't understand?",
"What is your dream hobby if time and money were no object?",
"How do you find the resources to support your hobbies?",
"What's a hobby you think everyone should try at least once?",
"How does your favorite hobby engage your creativity?",
"What's the best piece of advice you've received about pursuing your passions?",
"How do you stay engaged with your hobbies when life gets busy?",
"Do you feel your hobbies and passions are well balanced?",
"Have you ever felt judged for your hobbies? How did you handle it?",
"What's a hobby that you believe has made you a better person?",
"How have your passions influenced your life choices?",
"What's a passion project you're currently working on?",
"Have you ever taught someone else your hobby? How was that experience?",
"What's the biggest misconception people have about your hobby?",
"How do you react when a hobby becomes frustrating or difficult?",
"What's a hobby that you feel represents you?",
"How do your hobbies align with your values?",
"How do you incorporate your passions into your daily life?",
"What's a hobby that helps you feel productive?",
"Have your hobbies ever helped you through a difficult time?",
"How would you encourage others to pursue their passions?",
"What's the most valuable thing you've learned from your hobby?",
"Do you think hobbies are necessary for a fulfilling life? Why or why not?",
"What inspired you to pursue your current career or field of study?",
"How has your view of your career/education evolved over time?",
"What are the biggest challenges you face in your career/education?",
"Have you ever changed your career path or major? If so, what motivated the change?",
"How do you balance your career/educational pursuits with your personal life?",
"What skills or knowledge do you wish you had before entering your current career or field of study?",
"How have mentors or role models influenced your career or education?",
"What's the most rewarding part of your job or field of study?",
"Have you ever experienced a setback in your career or education? How did you overcome it?",
"What's the most valuable lesson you've learned in your career or education?",
"How do you handle stress and pressure in your career or education?",
"How do you continue learning and developing professionally?",
"What's a typical day like for you in your job or field of study?",
"How does your career or education align with your personal values and passions?",
"Have you ever doubted your career or educational choices? How did you handle these doubts?",
"What are your long-term career or educational goals?",
"What's the most unexpected thing you've encountered in your career or education?",
"What steps do you take when you have to make a major career or educational decision?",
"How do you handle criticism or feedback in your career or education?",
"How do you define success in your career or education?",
"What's the biggest risk you've taken in your career or education?",
"How do you maintain motivation and focus in your career or studies?",
"What role does creativity play in your career or education?",
"How does your job or field of study impact your identity and self-esteem?",
"Have you ever experienced a breakthrough or 'aha' moment in your career or education?", 
"How do you handle work-life balance?",
"What does professional growth look like to you?",
"How do you navigate politics or conflicts in your career or education?",
"Have you ever been faced with a moral or ethical dilemma in your career or education? How did you handle it?",
"How does your career or education affect your relationships?",
"What's the most interesting project you've worked on in your career or studies?",
"Have you ever felt like an imposter in your career or education?",
"What are your strategies for time management in your career or studies?",
"How do you recharge or take breaks from your career or education?",
"What do you wish others knew about your job or field of study?",
"How have your career or education changed you as a person?",
"What are your strengths in your career or education?",
"How does your career or education align with your life purpose?",
"How do you make difficult decisions in your career or education?",
"What makes you feel fulfilled in your career or education?",
"How does your career or education connect to your past experiences or upbringing?",
"How does your job or studies challenge you intellectually?",
"How do you handle failure or disappointment in your career or education?",
"How do you define and measure progress in your career or studies?",
"How has your career or education impacted your worldview?",
"What's the best career or educational advice you've ever received?",
"How does your career or education affect your mental health?",
"How have you grown or changed in your current job or course of study?",
"What skills or lessons from your job or studies do you apply to your personal life?",
"What is your dream job or field of study, and why?",
"What are your favorite ways to stay active?",
"How do you prioritize your mental health?",
"What does healthy eating mean to you?",
"How has your perception of your body changed over the years?",
"What self-care routines help you stay grounded?",
"How do you handle stress?",
"Do you have any techniques for maintaining a positive outlook?",
"How do you balance work and relaxation?",
"What do you do when you feel burnt out?",
"How important is sleep to you, and how do you ensure you're getting enough?",
"What's the most challenging aspect of maintaining your health?",
"What steps do you take when you feel you're getting ill?",
"How does your physical health affect your mental health, and vice versa?",
"What wellness goals do you have, and how are you working towards them?",
"Have you ever made a significant health-related change? What motivated you, and how did it go?",
"What's your approach to preventative health care?",
"How do you take care of your emotional health?",
"What activities make you feel most alive?",
"Have you ever struggled with a health issue? How did you cope?",
"How do you maintain your health during times of high stress or busy periods?",
"How do you integrate wellness practices into your daily routine?",
"How do you handle chronic pain or chronic illness?",
"What habits do you feel have the biggest impact on your health and wellness?",
"How do you approach setting and maintaining health-related boundaries?",
"How has aging affected your perception of health and wellness?",
"How do you nurture your mental health?",
"What role does nature play in your wellness routine?",
"What activities help you to recharge your energy?",  
"How do you motivate yourself to stick to health and wellness goals?",
"How has your relationship with food evolved over the years?",
"What role does technology play in your health and wellness routines?",
"How do you seek help when dealing with health concerns?",
"How do you cultivate self-love and self-acceptance?",
"How do you maintain your health and wellness during difficult times?",
"How does social interaction impact your wellbeing?",
"What misconceptions do you think society has about health and wellness?",
"How do you cope with feelings of anxiety or depression?",
"What are some health and wellness myths you've debunked in your own life?",
"How does your physical environment impact your health and wellness?",
"How has your cultural background influenced your approach to health and wellness?",
"What are some small things that make a big difference in your wellbeing?",
"How do you maintain health and wellness while traveling or on the go?",
"What role does spirituality or religion play in your health and wellness?",
"How do you handle medical appointments and procedures?",
"How do you foster a healthy relationship with aging and longevity?",
"How do you keep your mind sharp and engaged?",
"What impact do personal relationships have on your health and wellness?",
"How does your financial health impact your physical and mental wellbeing?",
"How do you cope with grief or loss?",
"What does living a 'balanced' life mean to you?",
"What values guide your decision-making?",
"How do you define success in life?",
"What role does religion or spirituality play in your life?",
"How do you view the concept of fate or destiny?",
"What is your perspective on the importance of education?",
"What is your stance on global climate change?",
"How do you interpret the concept of right and wrong?",
"How important is it to be politically aware and active?",
"What do you believe happens after death?",
"How do you perceive the balance between personal freedom and societal responsibility?",
"What are your views on the intersection of science and religion?",
"How do you view the balance of power in the world?",
"What are your thoughts on the role and impact of technology in society?",
"What are your beliefs about the origins of the universe?",
"How do you view the concept of justice?",
"What is your perspective on immigration?",
"How do you perceive the divide between the rich and the poor?",
"What do you believe is the purpose of human existence?",
"How do you view the concept of truth? Is it absolute or relative?",
"How do you view the role of government in society?",
"What is your perspective on war and peace?",
"How do you view the importance of art and culture in society?",
"What are your views on issues of gender equality?",
"How important is the concept of community to you?",
"What are your beliefs on the concept of race and ethnicity?",
"How do you view human rights? Are they universal or relative?",
"What are your thoughts on the role of the media in society?",
"What are your views on the concept of love and relationships?",
"What is your perspective on the role of animals in our lives and societies?",
"What are your thoughts on our responsibility to the environment?",
"How do you perceive the divide between urban and rural life?",
"What are your thoughts on the role and impact of social media?",
"What is your perspective on issues related to healthcare?",
"How do you view the concept of individualism versus collectivism?",
"What are your thoughts on the importance of history in our lives?",
"What are your beliefs about the role of businesses and corporations?",
"How do you view the concept of human nature?",
"What is your perspective on the concept of happiness?",
"What are your views on the existence of extraterrestrial life?",
"How important is the concept of personal space to you?",
"What are your thoughts on the relationship between parents and children?",
"How do you perceive the concept of aging and death?",
"What are your beliefs about the concept of knowledge and wisdom?",
"How do you view the role of music in society?",
"What are your thoughts on the concept of freedom of speech?",
"What is your perspective on the relationship between humans and machines?",
"What are your views on the concept of time?",
"How do you perceive the divide between physical and virtual spaces?",
"What are your beliefs about the concepts of identity and self?",
"How do you view the concept of change? Is it inherently good, bad, or neutral?",
"What's the most transformative experience you've ever had?",
"Can you remember a time when you had to make a difficult decision? What happened?",
"Have you ever had a brush with death? What was it like?",
"What was the happiest moment of your life?",
"Can you share an experience where you learned a valuable lesson from a child?",
"Have you ever had a supernatural or paranormal experience?",
"Describe a time when you experienced a major loss.",
"What's the most challenging thing you've ever done?",
"Share about a time you faced your biggest fear.",
"What was your most memorable birthday like?",
"Can you remember a time when you experienced immense joy?",
"Share an experience where you felt completely out of your comfort zone.",
"What was a life-changing encounter you had with a stranger?",
"Can you share an experience where you felt truly loved?",
"Have you ever been discriminated against or treated unfairly? How did you handle it?",
"What was the most physically demanding experience of your life?",
"Describe a time when you experienced a significant change in your life.",
"What was the most awe-inspiring natural landscape you ever experienced?",
"Can you share a time when you felt profoundly lonely?",
"Have you ever experienced a major health scare?",
"Share an experience that led to a major change in your beliefs.",
"Describe an experience where you felt a strong connection with an animal.",
"Can you share an experience where you felt truly proud of yourself?",
"Have you ever been in a situation where you were completely at the mercy of nature?",
"Describe a time when you had to stand up for what you believed in.",
"What's the most exciting adventure you've ever been on?",
"Share about a time you had to say goodbye to someone or something you loved.",
"Have you ever been through a natural disaster?",
"Can you share a time when you felt a deep sense of peace?",
"What was the most beautiful thing you ever saw?",
"Describe an experience where you had to face a major disappointment.",
"What was the most memorable journey or trip you ever took?",
"Can you share an experience that helped shape your character?",
"Have you ever experienced a miracle?",
"What was the most intense emotional experience of your life?",
"Can you share a time when you felt profoundly grateful?",
"Describe an experience where you had to forgive someone.",
"Have you ever had to overcome a deeply ingrained fear or phobia?",
"What's the most touching act of kindness you've ever witnessed or experienced?",
"Share an experience where you had to confront a personal weakness.",
"Have you ever experienced a crisis of faith?",
"Can you share a time when you felt a deep sense of connection with others?",
"What was the most humbling experience of your life?",
"Describe a time when you experienced a major personal victory.",
"Have you ever been lost, literally or metaphorically?",
"What was the most interesting cultural experience you've ever had?",
"Share about a time you experienced a significant failure.",
"Have you ever witnessed a historical event firsthand?",
"What was the most inspiring moment of your life?",
"Can you share a time when you felt a profound sense of wonder?",
"If you could design your ideal future, what would it look like?",
"How do you imagine the cities of the future?",
"What scientific breakthrough do you hope to see in your lifetime?",
"What do you think will be the biggest change in education over the next 50 years?",
"How will climate change affect our future?",
"What do you think the future of transportation looks like?",
"How might technology change the way we interact with each other in the future?",
"What do you hope will be different for the next generation?",
"If you could choose one aspect of society to evolve rapidly, what would it be?",
"How do you envision the role of AI in our future?",
"What are the future implications of genetic engineering?",
"How do you think the job market will change in the next 30 years?",
"What role do you see for virtual reality in the future?",
"How might space travel change our future?",
"What medical advancements do you hope to see in the future?",
"How do you think our diets will change in the future?",
"What are your thoughts on the future of renewable energy?",
"How will the internet evolve in the future?",
"What do you think the future of entertainment looks like?",
"How might the concept of 'family' change in the future?",
"How do you think the future generations will view our current society?",
"Do you think we'll achieve global peace in the future? Why or why not?",
"How will climate change reshape our world in the future?",
"How do you envision the future of social media?",
"What do you think the future holds for animal species?",
"How might the relationship between humans and nature change in the future?",
"What impact will automation have on the future?",
"How do you think the future of fashion will look?",
"What's your vision for the future of space exploration?",
"How might the concept of 'privacy' evolve in the future?",
"What do you hope will not change in the future?",
"What are the potential impacts of rising sea levels on future societies?",
"How do you see the future of art?",
"How might the concept of 'work' change in the future?",
"What are the potential future consequences of our current lifestyle?",
"How do you think technology will impact our mental health in the future?",
"How might future societies look back on our treatment of the environment?",
"What will be the future implications of advances in biotechnology?",
"How will nanotechnology shape our future?",
"How might the concept of 'nation' evolve in the future?",
"Do you believe there is a future where humans live in harmony with nature? Why or why not?",
"How do you envision the future of money and banking?",
"What are your thoughts on the future of human lifespan?",
"How might the concept of 'individuality' evolve in the future?",
"What role will robots play in our future?",
"How might future societies handle issues of mental health differently?",
"How do you think future generations will deal with our current political systems?",
"How might the concept of 'home' evolve in the future?",
"What's your vision for the future of healthcare?",
"How will quantum computing impact our future?" 
];
let drawPromptButton = document.querySelector('#draw-prompt-button');
let promptDisplay = document.querySelector('#prompt-display');

drawPromptButton.addEventListener('click', function() {
    if(prompts.length > 0) {
        let randomIndex = Math.floor(Math.random() * prompts.length);
        let randomPrompt = prompts[randomIndex];
        promptDisplay.textContent = randomPrompt;
    } else {
        promptDisplay.textContent = 'No prompts available.';
    }
});
